# Generated by Django 4.2.30 on 2026-04-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_financialgoal_recurringtransaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=14),
        ),
    ]
