from __future__ import annotations

from datetime import datetime, date
from decimal import Decimal

from django.contrib.auth import get_user_model
from django.core.management.base import BaseCommand
from django.db import transaction as db_transaction
from django.utils import timezone

from apps.finance.models import (
    Account,
    Budget,
    Category,
    FinancialGoal,
    RecurringTransaction,
    Transaction,
)


DEMO_PREFIX = "May 2026 Demo:"


class Command(BaseCommand):
    help = "Seed a diverse May 2026 demo dataset for the Personal Finance project."

    def add_arguments(self, parser):
        parser.add_argument(
            "--username",
            default="taikhoantest",
            help="Username to seed data for. Default: taikhoantest",
        )
        parser.add_argument(
            "--reset",
            action="store_true",
            help="Remove previously generated May 2026 demo records before inserting new ones.",
        )

    def handle(self, *args, **options):
        username = options["username"]
        reset = options["reset"]
        User = get_user_model()

        user = User.objects.filter(username=username).first()
        if not user:
            user = User.objects.create_user(
                username=username,
                email=f"{username}@example.com",
                password="12345678",
            )
            self.stdout.write(self.style.WARNING(
                f"User '{username}' did not exist, so it was created with password '12345678'."
            ))

        with db_transaction.atomic():
            if reset:
                self._reset_previous_demo(user)

            accounts = self._seed_accounts(user)
            categories = self._seed_categories(user)
            self._seed_budgets(user, categories)
            self._seed_goals(user)
            self._seed_recurring(user, accounts, categories)
            created_transactions = self._seed_transactions(user, accounts, categories)

        self.stdout.write(self.style.SUCCESS("May 2026 demo data has been seeded successfully."))
        self.stdout.write(f"User: {username}")
        self.stdout.write(f"Transactions created: {created_transactions}")
        self.stdout.write("Open Dashboard again and hard refresh with Ctrl + F5.")

    def _aware(self, year: int, month: int, day: int, hour: int = 9, minute: int = 0):
        return timezone.make_aware(
            datetime(year, month, day, hour, minute),
            timezone.get_current_timezone(),
        )

    def _reset_previous_demo(self, user):
        """Reverse balance effects and remove previous demo records generated by this command."""
        demo_transactions = list(
            Transaction.objects.filter(user=user, notes__startswith=DEMO_PREFIX)
            .select_related("account", "destination_account")
            .order_by("-occurred_at", "-id")
        )

        for tx in demo_transactions:
            if tx.type == "income":
                tx.account.balance -= tx.amount
                tx.account.save(update_fields=["balance"])
            elif tx.type == "expense":
                tx.account.balance += tx.amount
                tx.account.save(update_fields=["balance"])
            elif tx.type == "transfer" and tx.destination_account:
                tx.account.balance += tx.amount
                tx.destination_account.balance -= tx.amount
                tx.account.save(update_fields=["balance"])
                tx.destination_account.save(update_fields=["balance"])
            tx.delete()

        RecurringTransaction.objects.filter(user=user, notes__startswith=DEMO_PREFIX).delete()
        FinancialGoal.objects.filter(user=user, notes__startswith=DEMO_PREFIX).delete()
        Budget.objects.filter(user=user, month=5, year=2026).delete()

    def _get_or_create_account(self, user, name, acc_type, bank_name, initial_balance):
        account, created = Account.objects.get_or_create(
            user=user,
            name=name,
            defaults={
                "type": acc_type,
                "bank_name": bank_name,
                "currency": "VND",
                "initial_balance": Decimal(str(initial_balance)),
                "balance": Decimal(str(initial_balance)),
                "is_active": True,
            },
        )
        if not created:
            changed = False
            if not account.is_active:
                account.is_active = True
                changed = True
            if account.type != acc_type:
                account.type = acc_type
                changed = True
            if bank_name and account.bank_name != bank_name:
                account.bank_name = bank_name
                changed = True
            if changed:
                account.save()
        return account

    def _seed_accounts(self, user):
        accounts = {
            "MB Bank Main": self._get_or_create_account(user, "MB Bank Main", "bank", "MB Bank", 85000000),
            "Vietcombank Salary": self._get_or_create_account(user, "Vietcombank Salary", "bank", "Vietcombank", 32000000),
            "Emergency Savings": self._get_or_create_account(user, "Emergency Savings", "bank", "Techcombank", 25000000),
            "Momo E-Wallet": self._get_or_create_account(user, "Momo E-Wallet", "e-wallet", "Momo", 5500000),
            "ShopeePay Wallet": self._get_or_create_account(user, "ShopeePay Wallet", "e-wallet", "ShopeePay", 3500000),
            "Cash Wallet": self._get_or_create_account(user, "Cash Wallet", "cash", "", 6500000),
            "Travel Fund Wallet": self._get_or_create_account(user, "Travel Fund Wallet", "bank", "VPBank", 9000000),
        }
        return accounts

    def _get_or_create_category(self, user, name, cat_type, parent=None):
        category = Category.objects.filter(
            user=user,
            name=name,
            type=cat_type,
            parent=parent,
        ).first()
        if category:
            if not category.is_active:
                category.is_active = True
                category.save(update_fields=["is_active"])
            return category
        return Category.objects.create(
            user=user,
            name=name,
            type=cat_type,
            parent=parent,
            is_active=True,
        )

    def _seed_categories(self, user):
        c = {}

        # Income categories
        c["Salary"] = self._get_or_create_category(user, "Salary", "income")
        c["Freelance"] = self._get_or_create_category(user, "Freelance", "income")
        c["Bonus"] = self._get_or_create_category(user, "Bonus", "income")
        c["Refund"] = self._get_or_create_category(user, "Refund", "income")
        c["Interest"] = self._get_or_create_category(user, "Interest", "income")

        # Expense parent categories
        for name in [
            "Food", "Transport", "Shopping", "Bills", "Entertainment",
            "Health", "Education", "Travel", "Gifts", "Personal Care",
        ]:
            c[name] = self._get_or_create_category(user, name, "expense")

        # Food children
        c["Groceries"] = self._get_or_create_category(user, "Groceries", "expense", c["Food"])
        c["Restaurant"] = self._get_or_create_category(user, "Restaurant", "expense", c["Food"])
        c["Coffee"] = self._get_or_create_category(user, "Coffee", "expense", c["Food"])
        c["Breakfast"] = self._get_or_create_category(user, "Breakfast", "expense", c["Food"])

        # Transport children
        c["Grab/Taxi"] = self._get_or_create_category(user, "Grab/Taxi", "expense", c["Transport"])
        c["Fuel"] = self._get_or_create_category(user, "Fuel", "expense", c["Transport"])
        c["Parking"] = self._get_or_create_category(user, "Parking", "expense", c["Transport"])

        # Bills children
        c["Rent"] = self._get_or_create_category(user, "Rent", "expense", c["Bills"])
        c["Electricity"] = self._get_or_create_category(user, "Electricity", "expense", c["Bills"])
        c["Internet"] = self._get_or_create_category(user, "Internet", "expense", c["Bills"])
        c["Phone Bill"] = self._get_or_create_category(user, "Phone Bill", "expense", c["Bills"])

        # Shopping children
        c["Clothes"] = self._get_or_create_category(user, "Clothes", "expense", c["Shopping"])
        c["Electronics"] = self._get_or_create_category(user, "Electronics", "expense", c["Shopping"])
        c["Home Items"] = self._get_or_create_category(user, "Home Items", "expense", c["Shopping"])

        # Other children
        c["Gym"] = self._get_or_create_category(user, "Gym", "expense", c["Health"])
        c["Medicine"] = self._get_or_create_category(user, "Medicine", "expense", c["Health"])
        c["Online Course"] = self._get_or_create_category(user, "Online Course", "expense", c["Education"])
        c["Books"] = self._get_or_create_category(user, "Books", "expense", c["Education"])
        c["Movies"] = self._get_or_create_category(user, "Movies", "expense", c["Entertainment"])
        c["Subscription"] = self._get_or_create_category(user, "Subscription", "expense", c["Entertainment"])
        c["Weekend Trip"] = self._get_or_create_category(user, "Weekend Trip", "expense", c["Travel"])
        c["Skincare"] = self._get_or_create_category(user, "Skincare", "expense", c["Personal Care"])

        return c

    def _update_or_create_budget(self, user, category, amount, threshold=80):
        budget = Budget.objects.filter(
            user=user,
            category=category,
            month=5,
            year=2026,
            period="monthly",
        ).first()
        if budget:
            budget.amount = Decimal(str(amount))
            budget.alert_threshold = Decimal(str(threshold))
            budget.save()
            return budget
        return Budget.objects.create(
            user=user,
            category=category,
            amount=Decimal(str(amount)),
            period="monthly",
            month=5,
            year=2026,
            alert_threshold=Decimal(str(threshold)),
        )

    def _seed_budgets(self, user, c):
        self._update_or_create_budget(user, c["Food"], 6000000, 80)
        self._update_or_create_budget(user, c["Transport"], 2500000, 80)
        self._update_or_create_budget(user, c["Shopping"], 3500000, 80)
        self._update_or_create_budget(user, c["Bills"], 9500000, 85)
        self._update_or_create_budget(user, c["Entertainment"], 2200000, 80)
        self._update_or_create_budget(user, c["Health"], 1500000, 80)
        self._update_or_create_budget(user, c["Education"], 2500000, 80)
        self._update_or_create_budget(user, c["Travel"], 3000000, 75)
        self._update_or_create_budget(user, c["Personal Care"], 1200000, 80)
        self._update_or_create_budget(user, c["Gifts"], 1000000, 80)

    def _upsert_goal(self, user, name, target, current, deadline, notes):
        FinancialGoal.objects.update_or_create(
            user=user,
            name=name,
            defaults={
                "target_amount": Decimal(str(target)),
                "current_amount": Decimal(str(current)),
                "deadline": deadline,
                "notes": f"{DEMO_PREFIX} {notes}",
                "is_active": True,
            },
        )

    def _seed_goals(self, user):
        self._upsert_goal(user, "Emergency Fund", 80000000, 30000000, date(2026, 12, 31), "Build 4-6 months of safety savings.")
        self._upsert_goal(user, "New Laptop for Study", 35000000, 14500000, date(2026, 9, 15), "Save for a laptop used for study and project work.")
        self._upsert_goal(user, "Da Nang Summer Trip", 18000000, 7200000, date(2026, 7, 20), "Travel goal for summer vacation.")
        self._upsert_goal(user, "Motorbike Upgrade", 45000000, 10000000, date(2027, 1, 15), "Long-term goal for transportation upgrade.")
        self._upsert_goal(user, "SQL Course Certificate", 6000000, 2500000, date(2026, 8, 30), "Education goal related to database skills.")

    def _upsert_recurring(self, user, title, tx_type, amount, account, category, frequency, next_due_date, notes, destination_account=None):
        RecurringTransaction.objects.update_or_create(
            user=user,
            title=title,
            defaults={
                "type": tx_type,
                "amount": Decimal(str(amount)),
                "account": account,
                "destination_account": destination_account if tx_type == "transfer" else None,
                "category": category if tx_type != "transfer" else None,
                "frequency": frequency,
                "next_due_date": next_due_date,
                "auto_create": False,
                "notes": f"{DEMO_PREFIX} {notes}",
                "is_active": True,
            },
        )

    def _seed_recurring(self, user, a, c):
        self._upsert_recurring(user, "Monthly Salary", "income", 40000000, a["Vietcombank Salary"], c["Salary"], "monthly", date(2026, 6, 1), "Expected monthly salary.")
        self._upsert_recurring(user, "Room Rent", "expense", 7000000, a["MB Bank Main"], c["Rent"], "monthly", date(2026, 6, 5), "Monthly rent payment.")
        self._upsert_recurring(user, "Home Internet", "expense", 320000, a["MB Bank Main"], c["Internet"], "monthly", date(2026, 6, 8), "Monthly internet bill.")
        self._upsert_recurring(user, "Netflix Subscription", "expense", 260000, a["Momo E-Wallet"], c["Subscription"], "monthly", date(2026, 6, 10), "Entertainment subscription.")
        self._upsert_recurring(user, "Gym Membership", "expense", 550000, a["MB Bank Main"], c["Gym"], "monthly", date(2026, 6, 12), "Monthly gym membership.")
        self._upsert_recurring(user, "Emergency Fund Transfer", "transfer", 5000000, a["Vietcombank Salary"], None, "monthly", date(2026, 6, 2), "Automatic monthly transfer to emergency savings.", destination_account=a["Emergency Savings"])
        self._upsert_recurring(user, "Travel Saving Transfer", "transfer", 2000000, a["MB Bank Main"], None, "monthly", date(2026, 6, 3), "Monthly transfer to travel fund.", destination_account=a["Travel Fund Wallet"])

    def _create_tx(self, user, tx_type, amount, account, category, notes, occurred_at, destination_account=None):
        amount = Decimal(str(amount))
        tx = Transaction(
            user=user,
            type=tx_type,
            amount=amount,
            account=account,
            destination_account=destination_account if tx_type == "transfer" else None,
            category=category if tx_type != "transfer" else None,
            notes=f"{DEMO_PREFIX} {notes}",
            occurred_at=occurred_at,
        )
        tx.full_clean()
        tx.save()

        if tx_type == "income":
            account.balance += amount
            account.save(update_fields=["balance"])
        elif tx_type == "expense":
            account.balance -= amount
            account.save(update_fields=["balance"])
        elif tx_type == "transfer" and destination_account:
            account.balance -= amount
            destination_account.balance += amount
            account.save(update_fields=["balance"])
            destination_account.save(update_fields=["balance"])

        return tx

    def _seed_transactions(self, user, a, c):
        tx_data = [
            # Income
            ("income", 40000000, "Vietcombank Salary", "Salary", "May salary", 1, 9, 0, None),
            ("income", 8500000, "MB Bank Main", "Freelance", "Freelance dashboard UI project", 7, 18, 30, None),
            ("income", 3000000, "MB Bank Main", "Bonus", "Project completion bonus", 15, 14, 15, None),
            ("income", 750000, "Momo E-Wallet", "Refund", "Refund from returned online order", 18, 11, 10, None),
            ("income", 220000, "Emergency Savings", "Interest", "Bank interest income", 28, 9, 20, None),

            # Transfers
            ("transfer", 5000000, "Vietcombank Salary", None, "Transfer to emergency savings", 2, 10, 0, "Emergency Savings"),
            ("transfer", 2000000, "MB Bank Main", None, "Transfer to travel fund", 4, 16, 30, "Travel Fund Wallet"),
            ("transfer", 1500000, "MB Bank Main", None, "Top up Momo wallet", 5, 12, 0, "Momo E-Wallet"),
            ("transfer", 1000000, "MB Bank Main", None, "Withdraw cash for daily expenses", 9, 8, 45, "Cash Wallet"),
            ("transfer", 800000, "MB Bank Main", None, "Top up ShopeePay wallet", 19, 19, 30, "ShopeePay Wallet"),

            # Bills
            ("expense", 7000000, "MB Bank Main", "Rent", "Monthly room rent", 5, 9, 15, None),
            ("expense", 620000, "MB Bank Main", "Electricity", "Electricity bill", 10, 20, 10, None),
            ("expense", 320000, "MB Bank Main", "Internet", "Home internet bill", 8, 8, 30, None),
            ("expense", 180000, "Momo E-Wallet", "Phone Bill", "Mobile phone data package", 12, 12, 10, None),

            # Food
            ("expense", 680000, "Cash Wallet", "Groceries", "Groceries at WinMart", 3, 18, 20, None),
            ("expense", 450000, "Cash Wallet", "Groceries", "Weekly supermarket shopping", 12, 17, 40, None),
            ("expense", 920000, "MB Bank Main", "Restaurant", "Dinner with friends", 11, 20, 0, None),
            ("expense", 560000, "MB Bank Main", "Restaurant", "Family lunch", 24, 12, 45, None),
            ("expense", 95000, "Momo E-Wallet", "Coffee", "Highlands coffee", 6, 9, 15, None),
            ("expense", 120000, "Momo E-Wallet", "Coffee", "Milk tea and coffee", 16, 15, 10, None),
            ("expense", 65000, "Cash Wallet", "Breakfast", "Pho breakfast", 2, 7, 30, None),
            ("expense", 70000, "Cash Wallet", "Breakfast", "Banh mi and coffee", 14, 7, 45, None),
            ("expense", 980000, "MB Bank Main", "Restaurant", "Birthday dinner", 27, 19, 30, None),
            ("expense", 780000, "Cash Wallet", "Groceries", "Monthly grocery stock", 29, 18, 0, None),

            # Transport
            ("expense", 220000, "Momo E-Wallet", "Grab/Taxi", "Grab to school", 4, 8, 0, None),
            ("expense", 180000, "Momo E-Wallet", "Grab/Taxi", "Taxi after group meeting", 13, 21, 15, None),
            ("expense", 350000, "Cash Wallet", "Fuel", "Motorbike fuel", 6, 17, 0, None),
            ("expense", 320000, "Cash Wallet", "Fuel", "Fuel refill", 21, 18, 20, None),
            ("expense", 60000, "Cash Wallet", "Parking", "Parking fees", 22, 10, 10, None),

            # Shopping
            ("expense", 1450000, "ShopeePay Wallet", "Clothes", "New clothes for presentation", 9, 22, 15, None),
            ("expense", 1850000, "MB Bank Main", "Electronics", "External hard drive", 17, 15, 30, None),
            ("expense", 430000, "ShopeePay Wallet", "Home Items", "Desk lamp and storage box", 20, 10, 5, None),
            ("expense", 620000, "ShopeePay Wallet", "Skincare", "Skincare products", 25, 16, 0, None),

            # Entertainment / health / education / travel / gifts
            ("expense", 260000, "Momo E-Wallet", "Subscription", "Netflix subscription", 10, 13, 0, None),
            ("expense", 420000, "Momo E-Wallet", "Movies", "Cinema tickets", 18, 19, 40, None),
            ("expense", 550000, "MB Bank Main", "Gym", "Monthly gym membership", 12, 8, 0, None),
            ("expense", 360000, "Cash Wallet", "Medicine", "Medicine and vitamins", 23, 11, 30, None),
            ("expense", 2200000, "MB Bank Main", "Online Course", "SQL and database online course", 15, 22, 0, None),
            ("expense", 420000, "Cash Wallet", "Books", "Database textbook and notebook", 26, 14, 20, None),
            ("expense", 2600000, "Travel Fund Wallet", "Weekend Trip", "Weekend trip deposit", 24, 9, 10, None),
            ("expense", 850000, "Cash Wallet", "Gifts", "Birthday gift for friend", 27, 16, 30, None),
            ("expense", 620000, "MB Bank Main", "Personal Care", "Haircut and personal care", 30, 11, 0, None),
        ]

        count = 0
        for tx_type, amount, account_key, category_key, note, day, hour, minute, dest_key in tx_data:
            account = a[account_key]
            category = c[category_key] if category_key else None
            dest = a[dest_key] if dest_key else None
            self._create_tx(
                user=user,
                tx_type=tx_type,
                amount=amount,
                account=account,
                category=category,
                notes=note,
                occurred_at=self._aware(2026, 5, day, hour, minute),
                destination_account=dest,
            )
            count += 1
        return count
